#!/usr/bin/python3

from sys import argv
from math import sqrt


def factorization(n):
    factors = []

    if n % 2 == 0:
        factors.append((2, n // 2))
        return factors

    root = int(sqrt(n) + 1)

    for i in range(3, root, 2):
        if n % i == 0:
            factors.append((i, n // i))
            return factors
        if n % (root + i) == 0:
            factors.append((root + i, int(n//(root + i))))
            return factors

        if n % (root - i) == 0:
            factors.append((root - i, int(n//(root - i))))
            return factors

def main():
    if (len(argv) != 2):
        print("Usage: factors.py <file>")
        return

    with open(argv[1], "r") as file:
        for i in file:
            num = int(i.strip())
            factors = factorization(num)

            for n in factors:
                n1, n2 = n
                print("{}={}*{}".format(num, n2, n1))
                break


if __name__=="__main__":
    main()
